"use client";
import { useState } from "react";

export default function HtaccessGenerator() {
  const [rules, setRules] = useState({
    forceHttps: true,
    removeWww: false,
    addWww: false,
    customErrors: true,
    gzip: true,
    caching: true,
    blockIps: "",
    redirects: "",
    preventHotlinking: false,
    preventDirectoryListing: true,
    securityHeaders: true,
  });
  const [copied, setCopied] = useState(false);

  const generate = (): string => {
    const lines: string[] = ["# Generated by DevTools.run", "# https://devtools-site-delta.vercel.app/htaccess-generator", ""];

    if (rules.forceHttps) {
      lines.push("# Force HTTPS");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTPS} off");
      lines.push("RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    if (rules.removeWww) {
      lines.push("# Remove www");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]");
      lines.push("RewriteRule ^(.*)$ https://%1/$1 [R=301,L]");
      lines.push("");
    }

    if (rules.addWww) {
      lines.push("# Add www");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]");
      lines.push("RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]");
      lines.push("");
    }

    if (rules.customErrors) {
      lines.push("# Custom Error Pages");
      lines.push("ErrorDocument 404 /404.html");
      lines.push("ErrorDocument 500 /500.html");
      lines.push("ErrorDocument 403 /403.html");
      lines.push("");
    }

    if (rules.gzip) {
      lines.push("# Enable Gzip Compression");
      lines.push("<IfModule mod_deflate.c>");
      lines.push("  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css");
      lines.push("  AddOutputFilterByType DEFLATE application/javascript application/json");
      lines.push("  AddOutputFilterByType DEFLATE application/xml application/xhtml+xml");
      lines.push("  AddOutputFilterByType DEFLATE image/svg+xml");
      lines.push("</IfModule>");
      lines.push("");
    }

    if (rules.caching) {
      lines.push("# Browser Caching");
      lines.push("<IfModule mod_expires.c>");
      lines.push("  ExpiresActive On");
      lines.push("  ExpiresByType image/jpg \"access plus 1 year\"");
      lines.push("  ExpiresByType image/jpeg \"access plus 1 year\"");
      lines.push("  ExpiresByType image/gif \"access plus 1 year\"");
      lines.push("  ExpiresByType image/png \"access plus 1 year\"");
      lines.push("  ExpiresByType image/webp \"access plus 1 year\"");
      lines.push("  ExpiresByType text/css \"access plus 1 month\"");
      lines.push("  ExpiresByType application/javascript \"access plus 1 month\"");
      lines.push("  ExpiresByType image/svg+xml \"access plus 1 month\"");
      lines.push("  ExpiresDefault \"access plus 1 week\"");
      lines.push("</IfModule>");
      lines.push("");
    }

    if (rules.preventDirectoryListing) {
      lines.push("# Prevent Directory Listing");
      lines.push("Options -Indexes");
      lines.push("");
    }

    if (rules.securityHeaders) {
      lines.push("# Security Headers");
      lines.push("<IfModule mod_headers.c>");
      lines.push("  Header set X-Content-Type-Options \"nosniff\"");
      lines.push("  Header set X-Frame-Options \"SAMEORIGIN\"");
      lines.push("  Header set X-XSS-Protection \"1; mode=block\"");
      lines.push("  Header set Referrer-Policy \"strict-origin-when-cross-origin\"");
      lines.push("  Header set Permissions-Policy \"camera=(), microphone=(), geolocation=()\"");
      lines.push("</IfModule>");
      lines.push("");
    }

    if (rules.preventHotlinking) {
      lines.push("# Prevent Image Hotlinking");
      lines.push("RewriteEngine On");
      lines.push("RewriteCond %{HTTP_REFERER} !^$");
      lines.push("RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com [NC]");
      lines.push("RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC,L]");
      lines.push("");
    }

    if (rules.blockIps.trim()) {
      lines.push("# Block IPs");
      rules.blockIps.split("\n").filter(Boolean).forEach((ip) => {
        lines.push(`Deny from ${ip.trim()}`);
      });
      lines.push("");
    }

    if (rules.redirects.trim()) {
      lines.push("# Redirects");
      rules.redirects.split("\n").filter(Boolean).forEach((r) => {
        const [from, to] = r.split("→").map((s) => s.trim());
        if (from && to) lines.push(`Redirect 301 ${from} ${to}`);
      });
      lines.push("");
    }

    return lines.join("\n");
  };

  const output = generate();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold mb-2">.htaccess Generator</h1>
        <p className="text-[var(--text-secondary)]">
          Generate .htaccess rules for Apache servers. HTTPS redirect, gzip, caching, security headers, and more. Free htaccess generator.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="space-y-3">
          {[
            { key: "forceHttps", label: "Force HTTPS (301 redirect)" },
            { key: "removeWww", label: "Remove www" },
            { key: "addWww", label: "Add www" },
            { key: "customErrors", label: "Custom error pages (404, 500, 403)" },
            { key: "gzip", label: "Enable Gzip compression" },
            { key: "caching", label: "Browser caching (images, CSS, JS)" },
            { key: "preventDirectoryListing", label: "Prevent directory listing" },
            { key: "securityHeaders", label: "Security headers (X-Frame, CSP, etc.)" },
            { key: "preventHotlinking", label: "Prevent image hotlinking" },
          ].map(({ key, label }) => (
            <label key={key} className="flex items-center gap-3 cursor-pointer bg-[var(--bg-secondary)] border border-[var(--border)] rounded px-3 py-2">
              <input type="checkbox" checked={(rules as any)[key]} onChange={() => setRules({ ...rules, [key]: !(rules as any)[key] })} className="accent-purple-500" />
              <span className="text-sm text-white">{label}</span>
            </label>
          ))}

          <div className="bg-[var(--bg-secondary)] border border-[var(--border)] rounded-lg p-3">
            <label className="block text-xs text-gray-400 mb-1">Block IPs (one per line)</label>
            <textarea value={rules.blockIps} onChange={(e) => setRules({ ...rules, blockIps: e.target.value })} placeholder="192.168.1.1" className="w-full bg-[var(--bg-primary)] border border-[var(--border)] rounded px-2 py-1.5 text-white text-xs font-mono h-16 resize-none" />
          </div>

          <div className="bg-[var(--bg-secondary)] border border-[var(--border)] rounded-lg p-3">
            <label className="block text-xs text-gray-400 mb-1">Redirects (from → to, one per line)</label>
            <textarea value={rules.redirects} onChange={(e) => setRules({ ...rules, redirects: e.target.value })} placeholder="/old-page → /new-page" className="w-full bg-[var(--bg-primary)] border border-[var(--border)] rounded px-2 py-1.5 text-white text-xs font-mono h-16 resize-none" />
          </div>
        </div>

        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-sm font-medium">.htaccess Output</label>
            <button onClick={() => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 2000); }} className="text-xs text-purple-400 hover:text-purple-300">{copied ? "Copied!" : "Copy"}</button>
          </div>
          <pre className="bg-[var(--bg-secondary)] border border-[var(--border)] rounded p-3 text-xs font-mono text-emerald-400 overflow-auto max-h-[600px] whitespace-pre-wrap">{output}</pre>
        </div>
      </div>
    </div>
  );
}
