"use client";
import { useState } from "react";

export default function NginxConfig() {
  const [config, setConfig] = useState({
    serverName: "example.com",
    ssl: true,
    www: "redirect-to-non-www",
    gzip: true,
    http2: true,
    proxy: false,
    proxyPort: "3000",
    staticRoot: "/var/www/html",
    caching: true,
    securityHeaders: true,
    rateLimit: false,
    cors: false,
  });
  const [copied, setCopied] = useState(false);

  const generate = (): string => {
    const lines: string[] = ["# Generated by DevTools.run", `# Nginx config for ${config.serverName}`, ""];

    if (config.www === "redirect-to-non-www") {
      lines.push("server {");
      lines.push(`    listen 80;`);
      if (config.ssl) lines.push(`    listen 443 ssl${config.http2 ? " http2" : ""};`);
      lines.push(`    server_name www.${config.serverName};`);
      lines.push(`    return 301 https://${config.serverName}$request_uri;`);
      lines.push("}");
      lines.push("");
    }

    // HTTP redirect to HTTPS
    if (config.ssl) {
      lines.push("server {");
      lines.push("    listen 80;");
      lines.push(`    server_name ${config.serverName};`);
      lines.push(`    return 301 https://$server_name$request_uri;`);
      lines.push("}");
      lines.push("");
    }

    // Main server block
    lines.push("server {");
    if (config.ssl) {
      lines.push(`    listen 443 ssl${config.http2 ? " http2" : ""};`);
    } else {
      lines.push("    listen 80;");
    }
    lines.push(`    server_name ${config.serverName};`);
    lines.push("");

    if (config.ssl) {
      lines.push("    # SSL");
      lines.push(`    ssl_certificate /etc/letsencrypt/live/${config.serverName}/fullchain.pem;`);
      lines.push(`    ssl_certificate_key /etc/letsencrypt/live/${config.serverName}/privkey.pem;`);
      lines.push("    ssl_protocols TLSv1.2 TLSv1.3;");
      lines.push("    ssl_ciphers HIGH:!aNULL:!MD5;");
      lines.push("    ssl_prefer_server_ciphers on;");
      lines.push("");
    }

    if (config.proxy) {
      lines.push("    # Reverse Proxy");
      lines.push("    location / {");
      lines.push(`        proxy_pass http://127.0.0.1:${config.proxyPort};`);
      lines.push("        proxy_http_version 1.1;");
      lines.push("        proxy_set_header Upgrade $http_upgrade;");
      lines.push("        proxy_set_header Connection 'upgrade';");
      lines.push("        proxy_set_header Host $host;");
      lines.push("        proxy_set_header X-Real-IP $remote_addr;");
      lines.push("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
      lines.push("        proxy_set_header X-Forwarded-Proto $scheme;");
      lines.push("        proxy_cache_bypass $http_upgrade;");
      lines.push("    }");
    } else {
      lines.push(`    root ${config.staticRoot};`);
      lines.push("    index index.html index.htm;");
      lines.push("");
      lines.push("    location / {");
      lines.push("        try_files $uri $uri/ =404;");
      lines.push("    }");
    }
    lines.push("");

    if (config.gzip) {
      lines.push("    # Gzip");
      lines.push("    gzip on;");
      lines.push("    gzip_vary on;");
      lines.push("    gzip_min_length 1024;");
      lines.push("    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;");
      lines.push("");
    }

    if (config.caching) {
      lines.push("    # Static file caching");
      lines.push("    location ~* \\.(jpg|jpeg|png|gif|ico|css|js|webp|svg|woff2)$ {");
      lines.push("        expires 30d;");
      lines.push("        add_header Cache-Control \"public, immutable\";");
      lines.push("    }");
      lines.push("");
    }

    if (config.securityHeaders) {
      lines.push("    # Security headers");
      lines.push("    add_header X-Frame-Options \"SAMEORIGIN\" always;");
      lines.push("    add_header X-Content-Type-Options \"nosniff\" always;");
      lines.push("    add_header X-XSS-Protection \"1; mode=block\" always;");
      lines.push("    add_header Referrer-Policy \"strict-origin-when-cross-origin\" always;");
      lines.push("");
    }

    if (config.rateLimit) {
      lines.push("    # Rate limiting");
      lines.push("    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;");
      lines.push("    location /api/ {");
      lines.push("        limit_req zone=api burst=20 nodelay;");
      lines.push("        proxy_pass http://127.0.0.1:${config.proxyPort};");
      lines.push("    }");
      lines.push("");
    }

    if (config.cors) {
      lines.push("    # CORS");
      lines.push("    add_header Access-Control-Allow-Origin \"*\";");
      lines.push("    add_header Access-Control-Allow-Methods \"GET, POST, OPTIONS\";");
      lines.push("    add_header Access-Control-Allow-Headers \"Origin, Content-Type, Accept, Authorization\";");
      lines.push("");
    }

    lines.push("}");
    return lines.join("\n");
  };

  const output = generate();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold mb-2">Nginx Config Generator</h1>
        <p className="text-[var(--text-secondary)]">
          Generate Nginx server configuration. SSL, reverse proxy, gzip, caching, security headers. Free Nginx config generator.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="space-y-3">
          <div className="bg-[var(--bg-secondary)] border border-[var(--border)] rounded-lg p-4 space-y-3">
            <div>
              <label className="block text-xs text-gray-400 mb-1">Server Name</label>
              <input value={config.serverName} onChange={(e) => setConfig({ ...config, serverName: e.target.value })} className="w-full bg-[var(--bg-primary)] border border-[var(--border)] rounded px-3 py-2 text-white font-mono text-sm" />
            </div>
            {config.proxy && (
              <div>
                <label className="block text-xs text-gray-400 mb-1">Proxy Port</label>
                <input value={config.proxyPort} onChange={(e) => setConfig({ ...config, proxyPort: e.target.value })} className="w-full bg-[var(--bg-primary)] border border-[var(--border)] rounded px-3 py-2 text-white font-mono text-sm" />
              </div>
            )}
            {!config.proxy && (
              <div>
                <label className="block text-xs text-gray-400 mb-1">Document Root</label>
                <input value={config.staticRoot} onChange={(e) => setConfig({ ...config, staticRoot: e.target.value })} className="w-full bg-[var(--bg-primary)] border border-[var(--border)] rounded px-3 py-2 text-white font-mono text-sm" />
              </div>
            )}
          </div>

          {[
            { key: "ssl", label: "SSL/TLS (Let's Encrypt)" },
            { key: "http2", label: "HTTP/2" },
            { key: "proxy", label: "Reverse Proxy (Node.js, Python, etc.)" },
            { key: "gzip", label: "Gzip Compression" },
            { key: "caching", label: "Static File Caching" },
            { key: "securityHeaders", label: "Security Headers" },
            { key: "rateLimit", label: "Rate Limiting" },
            { key: "cors", label: "CORS Headers" },
          ].map(({ key, label }) => (
            <label key={key} className="flex items-center gap-3 cursor-pointer bg-[var(--bg-secondary)] border border-[var(--border)] rounded px-3 py-2">
              <input type="checkbox" checked={(config as any)[key]} onChange={() => setConfig({ ...config, [key]: !(config as any)[key] })} className="accent-purple-500" />
              <span className="text-sm text-white">{label}</span>
            </label>
          ))}
        </div>

        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-sm font-medium">nginx.conf</label>
            <button onClick={() => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 2000); }} className="text-xs text-purple-400 hover:text-purple-300">{copied ? "Copied!" : "Copy"}</button>
          </div>
          <pre className="bg-[var(--bg-secondary)] border border-[var(--border)] rounded p-3 text-xs font-mono text-emerald-400 overflow-auto max-h-[600px] whitespace-pre-wrap">{output}</pre>
        </div>
      </div>
    </div>
  );
}
